#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_LBRACE = 12,
  anon_sym_DQUOTE = 13,
  sym_text = 14,
  anon_sym_LBRACE_STAR = 15,
  aux_sym_smarty_comment_token1 = 16,
  anon_sym_RBRACE = 17,
  aux_sym_sq_attribute_value_fragment_token1 = 18,
  aux_sym_dq_attribute_value_fragment_token1 = 19,
  sym__start_tag_name = 20,
  sym__script_start_tag_name = 21,
  sym__style_start_tag_name = 22,
  sym__end_tag_name = 23,
  sym_erroneous_end_tag_name = 24,
  sym__implicit_end_tag = 25,
  sym_raw_text = 26,
  sym_comment = 27,
  sym_fragment = 28,
  sym_doctype = 29,
  sym__node = 30,
  sym_element = 31,
  sym_script_element = 32,
  sym_style_element = 33,
  sym_start_tag = 34,
  sym_script_start_tag = 35,
  sym_style_start_tag = 36,
  sym_self_closing_tag = 37,
  sym_end_tag = 38,
  sym_erroneous_end_tag = 39,
  sym_attribute = 40,
  sym_quoted_attribute_value = 41,
  sym_smarty_comment = 42,
  sym__attribute = 43,
  sym_sq_attribute_value_fragment = 44,
  sym_dq_attribute_value_fragment = 45,
  aux_sym_fragment_repeat1 = 46,
  aux_sym_start_tag_repeat1 = 47,
  aux_sym_sq_attribute_value_fragment_repeat1 = 48,
  aux_sym_dq_attribute_value_fragment_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_LBRACE] = "{",
  [anon_sym_DQUOTE] = "\"",
  [sym_text] = "text",
  [anon_sym_LBRACE_STAR] = "{*",
  [aux_sym_smarty_comment_token1] = "smarty_comment_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym_sq_attribute_value_fragment_token1] = "sq_attribute_value_fragment_token1",
  [aux_sym_dq_attribute_value_fragment_token1] = "dq_attribute_value_fragment_token1",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_smarty_comment] = "smarty_comment",
  [sym__attribute] = "_attribute",
  [sym_sq_attribute_value_fragment] = "attribute_value",
  [sym_dq_attribute_value_fragment] = "attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_sq_attribute_value_fragment_repeat1] = "sq_attribute_value_fragment_repeat1",
  [aux_sym_dq_attribute_value_fragment_repeat1] = "dq_attribute_value_fragment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_text] = sym_text,
  [anon_sym_LBRACE_STAR] = anon_sym_LBRACE_STAR,
  [aux_sym_smarty_comment_token1] = aux_sym_smarty_comment_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_sq_attribute_value_fragment_token1] = aux_sym_sq_attribute_value_fragment_token1,
  [aux_sym_dq_attribute_value_fragment_token1] = aux_sym_dq_attribute_value_fragment_token1,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_smarty_comment] = sym_smarty_comment,
  [sym__attribute] = sym__attribute,
  [sym_sq_attribute_value_fragment] = sym_attribute_value,
  [sym_dq_attribute_value_fragment] = sym_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_sq_attribute_value_fragment_repeat1] = aux_sym_sq_attribute_value_fragment_repeat1,
  [aux_sym_dq_attribute_value_fragment_repeat1] = aux_sym_dq_attribute_value_fragment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_smarty_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_sq_attribute_value_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dq_attribute_value_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_smarty_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_sq_attribute_value_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_dq_attribute_value_fragment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sq_attribute_value_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dq_attribute_value_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 14,
  [20] = 16,
  [21] = 21,
  [22] = 9,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 23,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 34,
  [41] = 33,
  [42] = 29,
  [43] = 28,
  [44] = 26,
  [45] = 27,
  [46] = 46,
  [47] = 37,
  [48] = 46,
  [49] = 25,
  [50] = 35,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 37,
  [59] = 37,
  [60] = 60,
  [61] = 61,
  [62] = 55,
  [63] = 37,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 61,
  [68] = 66,
  [69] = 69,
  [70] = 70,
  [71] = 37,
  [72] = 60,
  [73] = 70,
  [74] = 57,
  [75] = 56,
  [76] = 69,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 79,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 81,
  [87] = 87,
  [88] = 82,
  [89] = 77,
  [90] = 87,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 95,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 99,
  [105] = 105,
  [106] = 101,
  [107] = 96,
  [108] = 91,
  [109] = 94,
  [110] = 110,
  [111] = 95,
  [112] = 95,
  [113] = 95,
  [114] = 95,
  [115] = 105,
  [116] = 103,
  [117] = 102,
  [118] = 93,
  [119] = 110,
  [120] = 98,
  [121] = 102,
  [122] = 102,
  [123] = 102,
  [124] = 102,
  [125] = 92,
};

static inline bool sym_attribute_name_character_set_1(int32_t c) {
  return (c < '"'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || c == ' '))
    : (c <= '"' || (c < '<'
      ? (c < '/'
        ? c == '\''
        : c <= '/')
      : (c <= '>' || c == '{'))));
}

static inline bool sym_attribute_name_character_set_2(int32_t c) {
  return (c < '\''
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '\'' || (c < '<'
      ? (c < '/'
        ? c == '*'
        : c <= '/')
      : (c <= '>' || c == '{'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(41);
      if (!sym_attribute_name_character_set_1(lookahead)) ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(42);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 17:
      if (!sym_attribute_name_character_set_2(lookahead)) ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '*') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '*') ADVANCE(45);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(40);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '*') ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_STAR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_smarty_comment_token1);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(7);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_sq_attribute_value_fragment_token1);
      if (lookahead == '{') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_sq_attribute_value_fragment_token1);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_dq_attribute_value_fragment_token1);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_dq_attribute_value_fragment_token1);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 21, .external_lex_state = 2},
  [2] = {.lex_state = 21, .external_lex_state = 3},
  [3] = {.lex_state = 21, .external_lex_state = 3},
  [4] = {.lex_state = 21, .external_lex_state = 3},
  [5] = {.lex_state = 21, .external_lex_state = 3},
  [6] = {.lex_state = 21, .external_lex_state = 3},
  [7] = {.lex_state = 21, .external_lex_state = 2},
  [8] = {.lex_state = 21, .external_lex_state = 2},
  [9] = {.lex_state = 8, .external_lex_state = 4},
  [10] = {.lex_state = 8, .external_lex_state = 4},
  [11] = {.lex_state = 8, .external_lex_state = 4},
  [12] = {.lex_state = 8, .external_lex_state = 4},
  [13] = {.lex_state = 8, .external_lex_state = 4},
  [14] = {.lex_state = 2, .external_lex_state = 2},
  [15] = {.lex_state = 8, .external_lex_state = 2},
  [16] = {.lex_state = 3, .external_lex_state = 2},
  [17] = {.lex_state = 8, .external_lex_state = 2},
  [18] = {.lex_state = 8, .external_lex_state = 2},
  [19] = {.lex_state = 2, .external_lex_state = 2},
  [20] = {.lex_state = 3, .external_lex_state = 2},
  [21] = {.lex_state = 8, .external_lex_state = 2},
  [22] = {.lex_state = 8, .external_lex_state = 2},
  [23] = {.lex_state = 21, .external_lex_state = 3},
  [24] = {.lex_state = 21, .external_lex_state = 3},
  [25] = {.lex_state = 21, .external_lex_state = 3},
  [26] = {.lex_state = 21, .external_lex_state = 2},
  [27] = {.lex_state = 21, .external_lex_state = 3},
  [28] = {.lex_state = 21, .external_lex_state = 2},
  [29] = {.lex_state = 21, .external_lex_state = 3},
  [30] = {.lex_state = 21, .external_lex_state = 3},
  [31] = {.lex_state = 21, .external_lex_state = 2},
  [32] = {.lex_state = 21, .external_lex_state = 3},
  [33] = {.lex_state = 21, .external_lex_state = 3},
  [34] = {.lex_state = 21, .external_lex_state = 3},
  [35] = {.lex_state = 21, .external_lex_state = 2},
  [36] = {.lex_state = 21, .external_lex_state = 2},
  [37] = {.lex_state = 21, .external_lex_state = 2},
  [38] = {.lex_state = 21, .external_lex_state = 3},
  [39] = {.lex_state = 21, .external_lex_state = 2},
  [40] = {.lex_state = 21, .external_lex_state = 2},
  [41] = {.lex_state = 21, .external_lex_state = 2},
  [42] = {.lex_state = 21, .external_lex_state = 2},
  [43] = {.lex_state = 21, .external_lex_state = 3},
  [44] = {.lex_state = 21, .external_lex_state = 3},
  [45] = {.lex_state = 21, .external_lex_state = 2},
  [46] = {.lex_state = 21, .external_lex_state = 2},
  [47] = {.lex_state = 21, .external_lex_state = 3},
  [48] = {.lex_state = 21, .external_lex_state = 3},
  [49] = {.lex_state = 21, .external_lex_state = 2},
  [50] = {.lex_state = 21, .external_lex_state = 3},
  [51] = {.lex_state = 2, .external_lex_state = 2},
  [52] = {.lex_state = 3, .external_lex_state = 2},
  [53] = {.lex_state = 2, .external_lex_state = 2},
  [54] = {.lex_state = 3, .external_lex_state = 2},
  [55] = {.lex_state = 8, .external_lex_state = 4},
  [56] = {.lex_state = 8, .external_lex_state = 4},
  [57] = {.lex_state = 8, .external_lex_state = 4},
  [58] = {.lex_state = 2, .external_lex_state = 2},
  [59] = {.lex_state = 3, .external_lex_state = 2},
  [60] = {.lex_state = 8, .external_lex_state = 4},
  [61] = {.lex_state = 8, .external_lex_state = 4},
  [62] = {.lex_state = 8, .external_lex_state = 2},
  [63] = {.lex_state = 8, .external_lex_state = 4},
  [64] = {.lex_state = 1, .external_lex_state = 2},
  [65] = {.lex_state = 1, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 8, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 8, .external_lex_state = 2},
  [72] = {.lex_state = 8, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 5},
  [74] = {.lex_state = 8, .external_lex_state = 2},
  [75] = {.lex_state = 8, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 6},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 5},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 0, .external_lex_state = 5},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 0, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 0, .external_lex_state = 7},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 16, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 8},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 6, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 9},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 9},
  [117] = {.lex_state = 6, .external_lex_state = 2},
  [118] = {.lex_state = 16, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 8},
  [121] = {.lex_state = 6, .external_lex_state = 2},
  [122] = {.lex_state = 6, .external_lex_state = 2},
  [123] = {.lex_state = 6, .external_lex_state = 2},
  [124] = {.lex_state = 6, .external_lex_state = 2},
  [125] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_STAR] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(100),
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(4),
    [sym_script_start_tag] = STATE(70),
    [sym_style_start_tag] = STATE(68),
    [sym_self_closing_tag] = STATE(35),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_smarty_comment] = STATE(8),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [anon_sym_LBRACE_STAR] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(39), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [47] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(25), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(38), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [94] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(33), 1,
      sym_text,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(46), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(2), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [141] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LT_BANG,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(29), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym_text,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(48), 1,
      sym_end_tag,
    STATE(50), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(3), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [188] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LT_BANG,
    ACTIONS(44), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    ACTIONS(50), 1,
      sym_text,
    ACTIONS(53), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(56), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(50), 1,
      sym_self_closing_tag,
    STATE(66), 1,
      sym_style_start_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(6), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [232] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_LT_BANG,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(64), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    ACTIONS(70), 1,
      anon_sym_LBRACE_STAR,
    STATE(4), 1,
      sym_start_tag,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [276] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym_text,
    STATE(4), 1,
      sym_start_tag,
    STATE(35), 1,
      sym_self_closing_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(7), 8,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      sym_smarty_comment,
      aux_sym_fragment_repeat1,
  [320] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_attribute_name,
    ACTIONS(82), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(9), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [340] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_GT,
    ACTIONS(87), 1,
      anon_sym_SLASH_GT,
    ACTIONS(89), 1,
      sym_attribute_name,
    ACTIONS(91), 1,
      anon_sym_LBRACE_STAR,
    STATE(9), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [362] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_GT,
    ACTIONS(89), 1,
      sym_attribute_name,
    ACTIONS(91), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(93), 1,
      anon_sym_SLASH_GT,
    STATE(9), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [384] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_attribute_name,
    ACTIONS(91), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(95), 1,
      anon_sym_GT,
    ACTIONS(97), 1,
      anon_sym_SLASH_GT,
    STATE(11), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [406] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_attribute_name,
    ACTIONS(91), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(95), 1,
      anon_sym_GT,
    ACTIONS(99), 1,
      anon_sym_SLASH_GT,
    STATE(10), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [428] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      anon_sym_DQUOTE,
    ACTIONS(105), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(107), 1,
      aux_sym_dq_attribute_value_fragment_token1,
    STATE(90), 1,
      sym_dq_attribute_value_fragment,
    STATE(53), 2,
      sym_smarty_comment,
      aux_sym_dq_attribute_value_fragment_repeat1,
  [451] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_GT,
    ACTIONS(111), 1,
      sym_attribute_name,
    ACTIONS(113), 1,
      anon_sym_LBRACE_STAR,
    STATE(18), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [470] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_SQUOTE,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(119), 1,
      aux_sym_sq_attribute_value_fragment_token1,
    STATE(89), 1,
      sym_sq_attribute_value_fragment,
    STATE(54), 2,
      sym_smarty_comment,
      aux_sym_sq_attribute_value_fragment_repeat1,
  [493] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute_name,
    ACTIONS(113), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(121), 1,
      anon_sym_GT,
    STATE(21), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [512] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute_name,
    ACTIONS(113), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(123), 1,
      anon_sym_GT,
    STATE(22), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [531] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(107), 1,
      aux_sym_dq_attribute_value_fragment_token1,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_dq_attribute_value_fragment,
    STATE(53), 2,
      sym_smarty_comment,
      aux_sym_dq_attribute_value_fragment_repeat1,
  [554] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(119), 1,
      aux_sym_sq_attribute_value_fragment_token1,
    ACTIONS(127), 1,
      anon_sym_SQUOTE,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_sq_attribute_value_fragment,
    STATE(54), 2,
      sym_smarty_comment,
      aux_sym_sq_attribute_value_fragment_repeat1,
  [577] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute_name,
    ACTIONS(113), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(131), 1,
      anon_sym_GT,
    STATE(22), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [596] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(133), 1,
      sym_attribute_name,
    ACTIONS(136), 1,
      anon_sym_LBRACE_STAR,
    STATE(22), 4,
      sym_attribute,
      sym_smarty_comment,
      sym__attribute,
      aux_sym_start_tag_repeat1,
  [615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(139), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [629] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(143), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [643] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(147), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [657] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(153), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [671] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(155), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(161), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(163), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(167), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [727] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(173), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [741] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(173), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [755] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(175), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(179), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(185), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [797] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(139), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(189), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [825] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(191), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(191), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [853] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(179), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(175), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [881] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(163), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [895] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(161), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [909] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(153), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [923] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(155), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [937] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(197), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [951] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(189), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [965] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(197), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [979] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(147), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [993] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(185), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_STAR,
  [1007] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(204), 1,
      aux_sym_dq_attribute_value_fragment_token1,
    ACTIONS(199), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    STATE(51), 2,
      sym_smarty_comment,
      aux_sym_dq_attribute_value_fragment_repeat1,
  [1025] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(212), 1,
      aux_sym_sq_attribute_value_fragment_token1,
    ACTIONS(207), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
    STATE(52), 2,
      sym_smarty_comment,
      aux_sym_sq_attribute_value_fragment_repeat1,
  [1043] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(217), 1,
      aux_sym_dq_attribute_value_fragment_token1,
    ACTIONS(215), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    STATE(51), 2,
      sym_smarty_comment,
      aux_sym_dq_attribute_value_fragment_repeat1,
  [1061] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_LBRACE_STAR,
    ACTIONS(221), 1,
      aux_sym_sq_attribute_value_fragment_token1,
    ACTIONS(219), 2,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
    STATE(52), 2,
      sym_smarty_comment,
      aux_sym_sq_attribute_value_fragment_repeat1,
  [1079] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_EQ,
    ACTIONS(223), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      aux_sym_dq_attribute_value_fragment_token1,
    ACTIONS(189), 3,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACE_STAR,
  [1124] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      aux_sym_sq_attribute_value_fragment_token1,
    ACTIONS(189), 3,
      anon_sym_SQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACE_STAR,
  [1136] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_EQ,
    ACTIONS(223), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1178] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_attribute_value,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    ACTIONS(241), 1,
      anon_sym_DQUOTE,
    STATE(61), 1,
      sym_quoted_attribute_value,
  [1194] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_attribute_value,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    ACTIONS(247), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_quoted_attribute_value,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LT_SLASH,
    ACTIONS(251), 1,
      sym_raw_text,
    STATE(43), 1,
      sym_end_tag,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LT_SLASH,
    ACTIONS(255), 1,
      sym_raw_text,
    STATE(28), 1,
      sym_end_tag,
  [1245] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym__start_tag_name,
    ACTIONS(259), 1,
      sym__script_start_tag_name,
    ACTIONS(261), 1,
      sym__style_start_tag_name,
  [1258] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LT_SLASH,
    ACTIONS(263), 1,
      sym_raw_text,
    STATE(26), 1,
      sym_end_tag,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1289] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LT_SLASH,
    ACTIONS(265), 1,
      sym_raw_text,
    STATE(44), 1,
      sym_end_tag,
  [1302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1311] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_GT,
      sym_attribute_name,
      anon_sym_LBRACE_STAR,
  [1320] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym__script_start_tag_name,
    ACTIONS(261), 1,
      sym__style_start_tag_name,
    ACTIONS(267), 1,
      sym__start_tag_name,
  [1333] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SQUOTE,
    ACTIONS(271), 1,
      anon_sym_LBRACE,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1351] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LT_SLASH,
    STATE(33), 1,
      sym_end_tag,
  [1361] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LT_SLASH,
    STATE(41), 1,
      sym_end_tag,
  [1371] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LT_SLASH,
    STATE(34), 1,
      sym_end_tag,
  [1381] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym__end_tag_name,
    ACTIONS(277), 1,
      sym_erroneous_end_tag_name,
  [1391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LT_SLASH,
    STATE(40), 1,
      sym_end_tag,
  [1425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
  [1435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(287), 1,
      sym__end_tag_name,
  [1445] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
    ACTIONS(291), 1,
      anon_sym_LBRACE,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_GT,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym__doctype,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      aux_sym_doctype_token1,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
  [1493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym__end_tag_name,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_GT,
  [1528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_GT,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      aux_sym_smarty_comment_token1,
  [1549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_erroneous_end_tag_name,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_GT,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SQUOTE,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_GT,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
  [1584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_GT,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_SQUOTE,
  [1598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_DQUOTE,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_RBRACE,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_erroneous_end_tag_name,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      aux_sym_smarty_comment_token1,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      aux_sym_doctype_token1,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym__end_tag_name,
  [1675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      aux_sym_smarty_comment_token1,
  [1682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      aux_sym_smarty_comment_token1,
  [1689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      aux_sym_smarty_comment_token1,
  [1696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      aux_sym_smarty_comment_token1,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 232,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 340,
  [SMALL_STATE(11)] = 362,
  [SMALL_STATE(12)] = 384,
  [SMALL_STATE(13)] = 406,
  [SMALL_STATE(14)] = 428,
  [SMALL_STATE(15)] = 451,
  [SMALL_STATE(16)] = 470,
  [SMALL_STATE(17)] = 493,
  [SMALL_STATE(18)] = 512,
  [SMALL_STATE(19)] = 531,
  [SMALL_STATE(20)] = 554,
  [SMALL_STATE(21)] = 577,
  [SMALL_STATE(22)] = 596,
  [SMALL_STATE(23)] = 615,
  [SMALL_STATE(24)] = 629,
  [SMALL_STATE(25)] = 643,
  [SMALL_STATE(26)] = 657,
  [SMALL_STATE(27)] = 671,
  [SMALL_STATE(28)] = 685,
  [SMALL_STATE(29)] = 699,
  [SMALL_STATE(30)] = 713,
  [SMALL_STATE(31)] = 727,
  [SMALL_STATE(32)] = 741,
  [SMALL_STATE(33)] = 755,
  [SMALL_STATE(34)] = 769,
  [SMALL_STATE(35)] = 783,
  [SMALL_STATE(36)] = 797,
  [SMALL_STATE(37)] = 811,
  [SMALL_STATE(38)] = 825,
  [SMALL_STATE(39)] = 839,
  [SMALL_STATE(40)] = 853,
  [SMALL_STATE(41)] = 867,
  [SMALL_STATE(42)] = 881,
  [SMALL_STATE(43)] = 895,
  [SMALL_STATE(44)] = 909,
  [SMALL_STATE(45)] = 923,
  [SMALL_STATE(46)] = 937,
  [SMALL_STATE(47)] = 951,
  [SMALL_STATE(48)] = 965,
  [SMALL_STATE(49)] = 979,
  [SMALL_STATE(50)] = 993,
  [SMALL_STATE(51)] = 1007,
  [SMALL_STATE(52)] = 1025,
  [SMALL_STATE(53)] = 1043,
  [SMALL_STATE(54)] = 1061,
  [SMALL_STATE(55)] = 1079,
  [SMALL_STATE(56)] = 1092,
  [SMALL_STATE(57)] = 1102,
  [SMALL_STATE(58)] = 1112,
  [SMALL_STATE(59)] = 1124,
  [SMALL_STATE(60)] = 1136,
  [SMALL_STATE(61)] = 1146,
  [SMALL_STATE(62)] = 1156,
  [SMALL_STATE(63)] = 1168,
  [SMALL_STATE(64)] = 1178,
  [SMALL_STATE(65)] = 1194,
  [SMALL_STATE(66)] = 1210,
  [SMALL_STATE(67)] = 1223,
  [SMALL_STATE(68)] = 1232,
  [SMALL_STATE(69)] = 1245,
  [SMALL_STATE(70)] = 1258,
  [SMALL_STATE(71)] = 1271,
  [SMALL_STATE(72)] = 1280,
  [SMALL_STATE(73)] = 1289,
  [SMALL_STATE(74)] = 1302,
  [SMALL_STATE(75)] = 1311,
  [SMALL_STATE(76)] = 1320,
  [SMALL_STATE(77)] = 1333,
  [SMALL_STATE(78)] = 1343,
  [SMALL_STATE(79)] = 1351,
  [SMALL_STATE(80)] = 1361,
  [SMALL_STATE(81)] = 1371,
  [SMALL_STATE(82)] = 1381,
  [SMALL_STATE(83)] = 1391,
  [SMALL_STATE(84)] = 1399,
  [SMALL_STATE(85)] = 1407,
  [SMALL_STATE(86)] = 1415,
  [SMALL_STATE(87)] = 1425,
  [SMALL_STATE(88)] = 1435,
  [SMALL_STATE(89)] = 1445,
  [SMALL_STATE(90)] = 1455,
  [SMALL_STATE(91)] = 1465,
  [SMALL_STATE(92)] = 1472,
  [SMALL_STATE(93)] = 1479,
  [SMALL_STATE(94)] = 1486,
  [SMALL_STATE(95)] = 1493,
  [SMALL_STATE(96)] = 1500,
  [SMALL_STATE(97)] = 1507,
  [SMALL_STATE(98)] = 1514,
  [SMALL_STATE(99)] = 1521,
  [SMALL_STATE(100)] = 1528,
  [SMALL_STATE(101)] = 1535,
  [SMALL_STATE(102)] = 1542,
  [SMALL_STATE(103)] = 1549,
  [SMALL_STATE(104)] = 1556,
  [SMALL_STATE(105)] = 1563,
  [SMALL_STATE(106)] = 1570,
  [SMALL_STATE(107)] = 1577,
  [SMALL_STATE(108)] = 1584,
  [SMALL_STATE(109)] = 1591,
  [SMALL_STATE(110)] = 1598,
  [SMALL_STATE(111)] = 1605,
  [SMALL_STATE(112)] = 1612,
  [SMALL_STATE(113)] = 1619,
  [SMALL_STATE(114)] = 1626,
  [SMALL_STATE(115)] = 1633,
  [SMALL_STATE(116)] = 1640,
  [SMALL_STATE(117)] = 1647,
  [SMALL_STATE(118)] = 1654,
  [SMALL_STATE(119)] = 1661,
  [SMALL_STATE(120)] = 1668,
  [SMALL_STATE(121)] = 1675,
  [SMALL_STATE(122)] = 1682,
  [SMALL_STATE(123)] = 1689,
  [SMALL_STATE(124)] = 1696,
  [SMALL_STATE(125)] = 1703,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(125),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(69),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(116),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(117),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(92),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(76),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(103),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(102),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(55),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(121),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(62),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(122),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_smarty_comment, 3),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_smarty_comment, 3),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dq_attribute_value_fragment_repeat1, 2),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dq_attribute_value_fragment_repeat1, 2), SHIFT_REPEAT(124),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dq_attribute_value_fragment_repeat1, 2), SHIFT_REPEAT(51),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sq_attribute_value_fragment_repeat1, 2),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sq_attribute_value_fragment_repeat1, 2), SHIFT_REPEAT(123),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sq_attribute_value_fragment_repeat1, 2), SHIFT_REPEAT(52),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dq_attribute_value_fragment, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sq_attribute_value_fragment, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_htmlsmarty_external_scanner_create(void);
void tree_sitter_htmlsmarty_external_scanner_destroy(void *);
bool tree_sitter_htmlsmarty_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_htmlsmarty_external_scanner_serialize(void *, char *);
void tree_sitter_htmlsmarty_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_htmlsmarty(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_htmlsmarty_external_scanner_create,
      tree_sitter_htmlsmarty_external_scanner_destroy,
      tree_sitter_htmlsmarty_external_scanner_scan,
      tree_sitter_htmlsmarty_external_scanner_serialize,
      tree_sitter_htmlsmarty_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
